name: Simple Terraform Deployment Workflow Template

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      aws-iam-role-to-assume-name:
        required: true
        type: string
      working-directory:
        required: false
        type: string
    secrets:
      aws-account-id:
        required: true
      tf-vars:
        required: false

jobs:
  deploy_infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false
    - uses: kishaningithub/setup-tf-summarize@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Assume the role
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: arn:aws:iam::${{ secrets.aws-account-id }}:role/${{ inputs.aws-iam-role-to-assume-name }}
        role-session-name: deployInfra
    - name: Terraform Init
      run: terraform init
    - name: Terraform validate
      run: terraform validate 
    - name: Terraform Format
      run: terraform fmt -check
    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -input=false -out=tfplan
        echo "$(tf-summarize -md tfplan)" >> $GITHUB_STEP_SUMMARY
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
      run: terraform apply tfplan